server:
  port: 2001
spring:
  application:
    name: MI-EUREKA-CLIENT
  aop:
    auto: true # 开启AOP功能
  boot:
     admin:
      url: http://localhost:1000 # 应用服务监控
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/  # http://mitwo:2000/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号


# 服务提供中心 Map <Key String>
info:
  artifact : mi-eureka-client
  name: ${spring.application.name}
  description: 服务提供中心
  version : V1.0


swagger:
  docket:
    pro:
     title: spring-boot-starter-swagger
     description: Starter for swagger 2.x
     version: 1.1.0.RELEASE
     license: Apache License, Version 2.0
     licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
     termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
     contact:
       name: MIYAOW
       url: http://blog.csdn.net/fjnpysh
       email: dyc87112@qq.com
     base-package: com.mi.controller
     base-path: /**
     exclude-path: /error,/ops/**

    dev:
     title: spring-boot-starter-swagger
     description: Starter for swagger 2.x
     version: 1.1.0.RELEASE
     license: Apache License, Version 2.0
     licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
     termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
     contact:
       name: MIYAOW2
       url: http://blog.csdn.net/fjnpysh
       email: dyc87112@qq.com
     base-package: com.mi.controller
     base-path: /**
     exclude-path: /error,/ops/**